package star.sky.voyager.utils.init

object PackageNameHook {
    val PACKAGE_NAME_HOOKED = setOf(
        "com.xiaomi.aiasst.vision",
        "com.xiaomi.aireco",
        "com.miui.aod",
        "com.xiaomi.barrage",
        "com.android.browser",
        "com.milink.service",
        "com.android.externalstorage",
        "com.android.fileexplorer",
        "com.miui.gallery",
        "com.miui.guardprovider",
        "com.miui.home",
        "com.lbe.security.miui",
        "com.xiaomi.market",
        "com.miui.mediaeditor",
        "com.xiaomi.mirror",
        "com.xiaomi.misettings",
        "com.miui.mishare.connectivity",
        "com.miui.player",
        "com.miui.notes",
        "com.miui.packageinstaller",
        "com.miui.personalassistant",
        "com.miui.powerkeeper",
        "com.xiaomi.misubscreenui",
        "com.xiaomi.scanner",
        "com.miui.screenrecorder",
        "com.miui.screenshot",
        "com.miui.securitycenter",
        "com.android.settings",
        "com.android.systemui",
        "com.miui.contentextension",
        "com.android.updater",
        "com.miui.miwallpaper",
        "com.miui.weather2",
    )

    val AospShareHook = setOf(
        "android",
        "com.android.browser",
        "com.android.fileexplorer",
        "com.miui.gallery",
        "com.miui.home",
        "com.xiaomi.market",
        "com.miui.mediaeditor",
        "com.miui.mishare.connectivity",
        "com.miui.player",
        "com.xiaomi.scanner",
        "com.miui.screenrecorder",
        "com.miui.screenshot",
        "com.miui.securitycenter",
        "com.android.settings",
        "com.android.systemui",
        "com.miui.contentextension",
    )
}